apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-scraping-stats
spec:
  schedule: "0 20 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-scraping-stats
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - 'curl -X GET "api-cluster-ip-service:3000/article-stats/update-stats-tables" -H "accept: application/json"'
          restartPolicy: Never