apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapyd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scrapyd
  template:
    metadata:
      labels:
        component: scrapyd
    spec:
      # nodeSelector:
      #   node-id: "2"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: scrapyd
          image: charlymarchiaro/horse-engine-scrapyd
          ports:
            - containerPort: 6800
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1500m
              memory: 2500Mi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: DB_USER
              value: sa
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: DB_SERVER
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: horse_engine
            - name: SCRAPYD_LOG_LEVEL
              value: DEBUG
            - name: SPLASH_URL
              value: http://splash-cluster-ip-service:8050/
            - name: SCRAPOXY_IP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: scrapoxy-ip-address
                  key: SCRAPOXY_IP_ADDRESS
            - name: SCRAPOXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scrapoxy-password
                  key: SCRAPOXY_PASSWORD
