sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Decrypt service-account.json.enc file
  - openssl aes-256-cbc -K $encrypted_069e8a6480f9_key -iv $encrypted_069e8a6480f9_iv -in cicd-token.txt.enc -out cicd-token.txt -d
  - KUBERNETES_TOKEN=$(<cicd-token.txt)
  
  # Decrypt Kubernetes cluster certificate
  - echo "$KUBERNETES_CLUSTER_CERTIFICATE" | base64 --decode > cert.crt

  # Install Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  # Update kubectl
  - gcloud components update kubectl

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Build test images
  - docker build -t charlymarchiaro/horse-engine-client-test -f ./client/Dockerfile.dev ./client
  - docker build -t charlymarchiaro/horse-engine-scrapyd-test -f ./scrapyd/Dockerfile ./scrapyd

script:
  # Run tests
  - docker run charlymarchiaro/horse-engine-client-test npm test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - docker run charlymarchiaro/horse-engine-client-test /start.sh

deploy:
  # Run script deploy.sh
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
