apiVersion: skaffold/v2beta8
kind: Config
profiles:
build:
  local:
    # Don't push to dockerhub
    push: false
    useBuildkit: true
  artifacts:
    - image: charlymarchiaro/horse-engine-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.ts"
          - "**/*.css"
          - "**/*.scss"
          - "**/*.html"

    - image: charlymarchiaro/horse-engine-api
      context: api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.ts"
          - "**/*.css"
          - "**/*.scss"
          - "**/*.html"

    - image: charlymarchiaro/horse-engine-scrapyd
      context: scrapyd
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.py"
          - "**/*.txt"
          - "**/*.conf"
          - "**/*.cfg"

    - image: charlymarchiaro/horse-engine-splash
      context: splash
      docker:
        dockerfile: Dockerfile.dev

    # - image: charlymarchiaro/horse-engine-postgres
    #   context: postgres
    #   docker:
    #     dockerfile: Dockerfile.dev

deploy:
  statusCheckDeadlineSeconds: 6000
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/api-deployment.yaml
      - k8s/scrapyd-deployment.yaml
      - k8s/splash-deployment.yaml
      # - k8s/postgres-deployment.yaml
