apiVersion: skaffold/v1beta7
kind: Config
profiles:
build:
  local:
    # Don't push to dockerhub
    push: false
    useBuildkit: true
  artifacts:
    - image: charlymarchiaro/horse-engine-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
        "**/*.ts": .
        "**/*.css": .
        "**/*.scss": .
        "**/*.html": .

    - image: charlymarchiaro/horse-engine-api
      context: api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .

    - image: charlymarchiaro/horse-engine-scrapyd
      context: scrapyd
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.py": .
        "**/*.txt": .
        "**/*.conf": .
        "**/*.cfg": .

    - image: charlymarchiaro/pgadmin
      context: pgadmin
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/api-deployment.yaml
      - k8s/scrapyd-deployment.yaml
      - k8s/pgadmin-deployment.yaml
