apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  annotations:
    volume.beta.kubernetes.io/mount-options: dir_mode=0777,file_mode=0777,uid=5050,nobrl,cache=none
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
