apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 4200
          - path: /api/?(.*)
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 5000
          - path: /pgadmin/?(.*)
            backend:
              serviceName: pgadmin-cluster-ip-service
              servicePort: 7777
          - path: /scrapyd/?(.*)
            backend:
              serviceName: scrapyd-cluster-ip-service
              servicePort: 6800
