apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapoxy-pod-reaper-deployment
  namespace: reaper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scrapoxy-pod-reaper
  template:
    metadata:
      labels:
        component: scrapoxy-pod-reaper
    spec:
      serviceAccount: pod-reaper-service-account
      containers:
        - name: scrapoxy-pod-reaper
          image: target/pod-reaper
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 20m
              memory: 20Mi
          env:
            - name: SCHEDULE
              value: "55 * * * *"
            - name: MAX_DURATION
              value: "0h50m00s"
            - name: REQUIRE_LABEL_KEY
              value: component
            - name: REQUIRE_LABEL_VALUES
              value: scrapoxy
