apiVersion: apps/v1
kind: Deployment
metadata:
  name: splash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: splash
  template:
    metadata:
      labels:
        component: splash
    spec:
      containers:
        - name: splash
          image: scrapinghub/splash
          ports:
            - containerPort: 8050
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
