# binding the above cluster role (permissions) to the above service account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pod-reaper-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reaper-cluster-role
subjects:
  - kind: ServiceAccount
    name: pod-reaper-service-account
    namespace: reaper
