apiVersion: v1
kind: Service
metadata:
  name: postgres-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 11111
      targetPort: 5432
      protocol: TCP
  selector:
    component: postgres
