apiVersion: v1
kind: Service
metadata:
  name: scrapoxy-load-balancer
spec:
  type: LoadBalancer
  ports:
    - name: proxy
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: commander
      port: 8889
      targetPort: 8889
      protocol: TCP
  selector:
    component: scrapoxy
